"""added_capacity_description_fields

Revision ID: 733b433087ef
Revises: db8e1dc5d9b2
Create Date: 2025-08-31 17:42:54.647364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733b433087ef'
down_revision: Union[str, Sequence[str], None] = 'db8e1dc5d9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('BranchDescription', sa.String(), nullable=True))
    op.add_column('branches', sa.Column('Capacity', sa.Integer(), nullable=True))
    op.add_column('institutions', sa.Column('InstitutionDescription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'InstitutionDescription')
    op.drop_column('branches', 'Capacity')
    op.drop_column('branches', 'BranchDescription')
    # ### end Alembic commands ###
