"""replace_VisitorId_with_VisitorName

Revision ID: db8e1dc5d9b2
Revises: f2ebf23dfc5d
Create Date: 2025-08-31 03:49:33.114819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8e1dc5d9b2'
down_revision: Union[str, Sequence[str], None] = 'f2ebf23dfc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor_logs', sa.Column('VisitorName', sa.String(), nullable=True))
    op.drop_constraint(op.f('visitor_logs_VisitorId_fkey'), 'visitor_logs', type_='foreignkey')
    op.drop_column('visitor_logs', 'VisitorId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor_logs', sa.Column('VisitorId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('visitor_logs_VisitorId_fkey'), 'visitor_logs', 'visitors', ['VisitorId'], ['UserId'])
    op.drop_column('visitor_logs', 'VisitorName')
    # ### end Alembic commands ###
